# Generated by Django 4.2.1 on 2023-06-07 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\+?[1-9][0-9]{7,14}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='verification_type',
            field=models.CharField(choices=[('register', 'Register'), ('login', 'Login')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\+?[1-9][0-9]{7,14}$', 'Enter a valid phone number.')]),
        ),
        migrations.AlterUniqueTogether(
            name='verificationcode',
            unique_together={('phone', 'verification_type')},
        ),
    ]
