# Generated by Django 4.2.1 on 2023-06-14 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verificationcode_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
