# Generated by Django 4.2.1 on 2023-06-14 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\+?[1-9][0-9]{7,14}$', 'Enter a valid phone number.')]),
        ),
    ]
