# Generated by Django 4.2.1 on 2023-06-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='desc_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='desc_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name_uz',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
