# Generated by Django 4.2.1 on 2023-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_desc_en_course_desc_ru_course_desc_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='desc_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Price'),
        ),
    ]
