# Generated by Django 4.2.4 on 2023-08-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
        ("course", "0004_alter_course_desc_alter_course_desc_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="category.category",
            ),
        ),
    ]
