# Generated by Django 4.2.4 on 2023-08-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_category_level_category_lft_category_rght_and_more"),
        ("course", "0005_alter_course_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.AddField(
            model_name="course",
            name="categories",
            field=models.ManyToManyField(
                related_name="courses", to="category.category"
            ),
        ),
    ]
