# Generated by Django 4.2.4 on 2023-08-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0006_remove_course_category_course_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecontent",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
