# Generated by Django 4.2.4 on 2023-08-11 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_coursecontent_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursecontent",
            name="time",
        ),
    ]
