# Generated by Django 4.2.4 on 2023-08-10 09:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0007_alter_coursecontent_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="desc",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="desc_en",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="desc_ru",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="desc_uz",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                null=True, verbose_name="Description"
            ),
        ),
    ]
