# Generated by Django 4.2.4 on 2023-08-11 12:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0008_alter_course_desc_alter_course_desc_en_and_more"),
        ("course", "0008_remove_coursecontent_time"),
    ]

    operations = []
