# Generated by Django 4.2.4 on 2023-08-14 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0009_merge_20230811_1748"),
        ("course", "0010_alter_course_slug"),
    ]

    operations = []
