# Generated by Django 4.2.4 on 2023-08-24 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course", "0012_alter_coursecontent_video_courseprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseapply",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
