# Generated by Django 4.2.4 on 2023-08-07 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0005_alter_course_category"),
        ("category", "0001_initial"),
        ("common", "0004_alter_log_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationform",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application",
                to="category.category",
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
