# Generated by Django 4.2.4 on 2023-08-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_aboutus_video_file_aboutus_video_poster_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contactus",
            name="location",
        ),
        migrations.AddField(
            model_name="contactus",
            name="lat",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="contactus",
            name="lng",
            field=models.FloatField(null=True),
        ),
    ]
