# Generated by Django 4.2.4 on 2023-08-10 15:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0008_banner_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="description",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
