# Generated by Django 4.2.4 on 2023-08-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rate",
            field=models.CharField(
                choices=[
                    (1, "Choice One"),
                    (2, "Choice Two"),
                    (3, "Choice Three"),
                    (4, "Choice Four"),
                    (5, "Choice Five"),
                ],
                max_length=20,
            ),
        ),
    ]
