# Generated by Django 4.2.4 on 2023-08-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0012_alter_testimonial_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rate",
            field=models.IntegerField(
                choices=[
                    (1, "Choice One"),
                    (2, "Choice Two"),
                    (3, "Choice Three"),
                    (4, "Choice Four"),
                    (5, "Choice Five"),
                ]
            ),
        ),
    ]
