# Generated by Django 4.2.4 on 2023-08-12 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_board"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="is_active",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
