# Generated by Django 4.2.4 on 2023-08-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0015_board_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="board",
            old_name="text",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="board",
            name="is_active",
        ),
        migrations.CreateModel(
            name="BoardLogoText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("logo", models.ImageField(upload_to="")),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boards",
                        to="common.board",
                    ),
                ),
            ],
        ),
    ]
