# Generated by Django 4.2.4 on 2023-08-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0016_rename_text_board_title_remove_board_is_active_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BoardLogoText",
            new_name="BoardLogoTitle",
        ),
        migrations.AddField(
            model_name="board",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
