# Generated by Django 4.2.4 on 2023-08-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0017_rename_boardlogotext_boardlogotitle_board_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(null=True, upload_to="blog/images/"),
        ),
    ]
