# Generated by Django 4.2.4 on 2023-08-24 09:40

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0018_blog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutUsFull",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("text", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="about/images/"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aboutus",
            name="details",
            field=models.ManyToManyField(
                related_name="details", to="common.aboutusfull"
            ),
        ),
    ]
