# Generated by Django 4.2.4 on 2023-08-24 10:59

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0019_aboutusfull_aboutus_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
    ]
