# Generated by Django 4.2.4 on 2023-08-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("holder_name", models.CharField(max_length=50)),
                ("number", models.CharField(max_length=16)),
                ("exp_month", models.IntegerField()),
                ("exp_year", models.IntegerField()),
                ("cvc", models.CharField(max_length=10)),
            ],
        ),
    ]
